version: '3'

tasks:
  # 開発用
  dev:frontend:
    desc: Start Next.js development server
    dir: frontend
    cmds:
      - pnpm dev

  dev:backend:
    desc: Start Go backend development server
    dir: backend
    cmds:
      - go run cmd/server/main.go

  # ビルド用
  build:lambda:api:
    desc: Build API Lambda container image
    cmds:
      - ./scripts/build-lambda-api.sh

  build:lambda:notification:
    desc: Build notification Lambda ZIP package
    cmds:
      - ./scripts/build-lambda-notification.sh

  build:all:
    desc: Build all Lambda functions
    deps: [build:lambda:api, build:lambda:notification]

  # Terraform用（ローカル実行）
  terraform:init:
    desc: Initialize Terraform
    dir: infra
    cmds:
      - terraform init

  terraform:plan:
    desc: Plan Terraform changes (local)
    deps: [terraform:init]
    dir: infra
    cmds:
      - terraform plan

  terraform:apply:
    desc: Create basic infrastructure (local)
    deps: [terraform:init]
    dir: infra
    cmds:
      - terraform apply -auto-approve

  # 統合デプロイタスク
  deploy:
    desc: Build and deploy everything (build → ECR push → Lambda deploy → EventBridge setup)
    deps: [build:all]
    cmds:
      - ./scripts/deploy-full.sh

  deploy:api:
    desc: Deploy only API Lambda (build → ECR push → update)
    deps: [build:lambda:api]
    cmds:
      - ./scripts/deploy-api.sh

  deploy:notification:
    desc: Deploy only notification Lambda (build → update)
    deps: [build:lambda:notification]
    cmds:
      - ./scripts/deploy-notification.sh

  # 監視・ログ確認タスク
  logs:api:
    desc: View API Lambda logs
    dir: infra
    cmds:
      - ./scripts/logs-api.sh

  logs:notification:
    desc: View notification Lambda logs
    dir: infra
    cmds:
      - ./scripts/logs-notification.sh

  status:
    desc: Check deployment status and costs
    dir: infra
    cmds:
      - ./scripts/status.sh
