version: '3'

tasks:
  # 開発用
  dev:frontend:
    desc: Start Next.js development server
    dir: frontend
    cmds:
      - pnpm dev

  dev:backend:
    desc: Start Go backend development server
    dir: backend
    cmds:
      - go run cmd/server/main.go

  # ビルド用
  build:lambda:api:
    desc: Build API Lambda container image
    cmds:
      - ./scripts/build-lambda-api.sh

  build:lambda:notification:
    desc: Build notification Lambda ZIP package
    cmds:
      - ./scripts/build-lambda-notification.sh

  # Terraform用
  terraform:init:
    desc: Initialize Terraform
    dir: infra
    cmds:
      - terraform init

  terraform:plan:
    desc: Plan Terraform changes
    dir: infra
    deps: [terraform:init]
    cmds:
      - terraform plan

  terraform:apply:
    desc: Apply Terraform changes
    dir: infra
    deps: [terraform:init]
    cmds:
      - terraform apply -auto-approve

  # デプロイ用
  deploy:backend:
    desc: Deploy backend Lambda function
    deps: [build:lambda:api]
    cmds:
      - ./scripts/deploy-backend.sh

