version: '3'

tasks:
  # 開発用
  dev:frontend:
    desc: Start Next.js development server
    dir: frontend
    cmds:
      - pnpm dev

  dev:backend:
    desc: Start Go backend development server
    dir: backend
    cmds:
      - go run cmd/server/main.go

  # ビルド用
  build:lambda:api:
    desc: Build API Lambda container image
    cmds:
      - ./scripts/build-lambda-api.sh

  build:lambda:notification:
    desc: Build notification Lambda ZIP package
    cmds:
      - ./scripts/build-lambda-notification.sh

  build:all:
    desc: Build all Lambda functions
    deps: [build:lambda:api, build:lambda:notification]

  # Terraform用（ローカル実行）
  terraform:init:
    desc: Initialize Terraform
    dir: infra
    cmds:
      - terraform init

  terraform:plan:
    desc: Plan Terraform changes (local)
    deps: [terraform:init]
    dir: infra
    cmds:
      - terraform plan

  # CD環境用
  deploy:
    desc: Deploy everything including Lambda functions (CD only)
    deps: [build:all, terraform:init]
    dir: infra
    cmds:
      - terraform apply -auto-approve
